sudo: required
language: java
jdk:
- openjdk8
services:
- docker

cache:
  directories:
  - .autoconf
  - $HOME/.m2

env:
  global:
  - SHA=$(git rev-parse HEAD)

before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- chmod +x server/mvnw
- docker pull openjdk:8-jdk-alpine
- docker-compose run -p 8092:8092 -d --rm performance-tests-env
- export PERFORMANCE_TESTS_ENV_URL=(docker-machine ip)

- curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/kubectl
- chmod +x ./kubectl
- mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
- kubectl version --short --client

#- curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator

# Test & Build SpringBoot app
script:
- cd server
- mvn clean
- mvn test
- mvn clean package
- mvn gatling:test -Dspring.profiles.active=test
- cd ..
- docker-compose down

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
