sudo: true
language: java
jdk:
- openjdk8
services:
- docker

cache:
  directories:
  - .autoconf
  - $HOME/.m2

before_install:
- chmod +x server/mvnw
- docker-compose run -p 8092:8092 -d --rm performance-tests-env


# Test & Build SpringBoot app
script:
- cd server
- mvn clean package -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
- mvn gatling:test -Dspring.profiles.active=test -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn # run performance tests
- cd ..
- docker-compose down

after_success:
- docker build -t mavsvl/notification-service-client ./client
- docker build -t mavsvl/notification-service-nginx ./nginx
- docker build -t mavsvl/notification-service-server ./server
# Log in to the Docker CLI
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# Take those images and push it to the docker hub
- docker push mavsvl/notification-service-client
- docker push mavsvl/notification-service-nginx
- docker push mavsvl/notification-service-server

#deploy:
#  provider: elasticbeanstalk
#  region: eu-west-1
#  app: notification-service
#  env: MultiDocker-env
#  bucket_name: elasticbeanstalk-eu-west-1-728900069172
#  bucket_path: notification-service
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY