sudo: required
language: java
jdk:
- openjdk8
services:
- docker

cache:
  directories:
  - '$HOME/.m2/repository'

env:
  global:
  - SHA=$(git rev-parse HEAD)

before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_USERNAME" --password-stdin
- chmod +x mvnw
- docker pull openjdk:8-jdk-alpine
- docker-compose run -p 8092:8092 -d --rm performance-tests-env
- export PERFORMANCE_TESTS_ENV_URL=(docker-machine ip)

# Test & Build SpringBoot app
script:
- mvn test
- mvn clean package
- mvn gatling:test -Dspring.profiles.active=test
- docker-compose down

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
