version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
    - "3050:80"
  postgres:
    image: postgres:latest
  performance-tests-env:
    build:
      context: ./server
    environment:
    - CI=true
    - spring.profiles.active=test
    - server.port=8092
    ports:
    - "8092:8092"
    command: ["java", "-jar", "app.jar"]
  notification-service:
    build:
      context: ./server
    environment:
    - PGUSER=postgres
    - PGURL=jdbc:postgresql://postgres:5432/postgres
    - PGPASSWORD=postgres_password
    command: ["java", "-jar", "app.jar"]