FROM openjdk:8-jdk-alpine as build
WORKDIR /workspace/app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src

ARG spring.profiles.active=test
ENV spring.profiles.active=$spring.profiles.active
RUN ./mvnw install -DskipTests=true

RUN ./mvnw test

CMD ["java", "-jar", "target/notification-service-0.0.1-SNAPSHOT.jar"]