version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
    - '3050:80'
  postgres:
    image: postgres:latest
  notification-service:
    build:
      dockerfile: Dockerfile.dev
      context: .
    environment:
    - PGUSER=postgres
    - PGURL=jdbc:postgresql://postgres:5432/postgres
    - PGPASSWORD=postgres_password