spring:
  application:
    name: notification-service
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
logging:
  level:
    com:
      example:
        notificationservice: INFO
    org:
      springframework:
        aop:
          interceptor: INFO
server:
  port: 8091